### ISSUE TITLE
Style Email Template and Applicant Response Pages

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#121]
We need to style the [email template](https://github.com/MAPC/youth-match-v2/tree/develop/app/views/job_offer_mailer) that lets young people pick if they will accept their job. We also need to style the [decline](https://github.com/MAPC/youth-match-v2/blob/develop/app/views/offers/decline.html.erb) and [accept](https://github.com/MAPC/youth-match-v2/blob/develop/app/views/offers/accept.html.erb) templates. Alicia was hoping to have the City of Boston logo on these. Otherwise, use your best judgment.

**Comment by allthesignals** [comment]
@mzagaja I can start with the e-mail template without data (i think) but what's the quickest way to a test page for the decline/accept templates? do I run a test server?

**Comment by allthesignals** [comment]
Alright, I was wrong about the mailer preview - I need context data to test it (catching up from 74 new commits since I last looked at this project). 

`undefined method `applicant' for nil:NilClass`

```              
  def job_offer_email(user)
    @user = user
    @offer = user.applicant.offer
    @position = user.applicant.offer.position
    @accept_url  = 'http://dyee.mapc.org/offers/accept?email=' + user.email + '&token=' + user.authentication_token
    @decline_url = 'http://dyee.mapc.org/offers/decline?email=' + user.email + '&token=' + user.authentication_token
```

**Comment by mzagaja** [comment]
Start a local server and then point your browser to:

http://127.0.0.1:3000/rails/mailers/job_offer_mailer/job_offer_email.html for the email template

For an accept or decline you'll need to have a local user created. The user will need to have an associated applicant, and then an associated offer.

```
Applicant.create(first_name: 'Test', last_name: 'Test')
User.create(email: 'mzagaja@alum.wpi.edu', authentication_token: 'abc', user: Applicant.last)
Position.create(title: 'Test Position')
Offer.create(applicant: Applicant.last, position: Position.last)
```

Go to URL `http://127.0.0.1:3000/offers/accept?email=mzagaja@alum.wpi.edu&token=abc` for accept
`http://127.0.0.1:3000/offers/decline?email=mzagaja@alum.wpi.edu&token=abc` for decline.

**Comment by allthesignals** [comment]
@mzagaja thank you! Note my comment about the email template when you get a sec.

```User.create(email: 'mzagaja@alum.wpi.edu', authentication_token: 'abc', user: Applicant.last)```
I think there's a mistake here - `user` doesn't seem like an attribute of `User` - maybe it was `applicant`? If so, I think something is preventing it from persisting to the db (it immediately rolls back)...

**Comment by mzagaja** [comment]
Yep you're right. Should be `applicant`. Weird that it rolls back. You can try creating without an authentication token since it will create one automatically. Maybe it didn't like I was passing that attribute. I bet the issue is user needs a password attribute `password: 'test'`

**Comment by allthesignals** [comment]
Thanks, Matt - it looks like some scaffolding was used for the styling. It's colliding with the view-specific styles (weirdly, it doesn't take precedence).
