### ISSUE TITLE
Send Texts to "Exempt Select" Job Offered Youth

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#143]
Send the following texts to exempt youth who were offered a job:

To finish the City of Boston summer job hiring process, you MUST upload documents bit.ly/summerjobdocs & complete tasks in your account bit.ly/successlinklogin

You must also bring those documents in person to verify at YEE: 1483 Tremont St, Boston, MA 02120, weekdays 2-7pm, OR come this Saturday 12-4

**Comment by mzagaja** [comment]
Done
