### ISSUE TITLE
Evaluate "editing data in browser" options

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#149]
Fieldbook, Airtable, Google sheets etc.

**Comment by mzagaja** [comment]
After doing further research, I do not think using a Fieldbook/Airtable/Google Sheets will work well for us. Fieldbook and Airtable do not have the geographic functionality we use with Postgres to try and use this as a "drop-in" replacement for our Postgres database. We also would lose a lot of the functions and previous coding we already have done with ActiveRecord, so it would add a bunch of work to then create this external dependency that would then reduce performance. I don't think these would scale to work with the algorithm properly, and it would require a lot of custom work to map the models to tables in the world of Fieldbook/Airtable with a large risk that users can break or change information.

Another issue is that we're tightly coupled with ICIMS. We are dependentant upon ICIMS for most of our data, and if we make changes it is up to us to push it back to ICIMS. ICIMS API has not proven to be the most reliable thing, and also is at risk of breaking. If we constrain the editing that can happen on our end to the things that we exclusively handle, we reduce the risk of the app breaking in the future when ICIMS makes changes to their API.

In the end the best place for data to be edited is at ICIMS, with us providing some read only interfaces for the data we get from there, along with the GUI for the functionality specific to our app where we merely update ICIMS as a courtesy. I would feel more ok exploring this if ICIMS was not a factor, but even then my sense is Fieldbook and Airtable give users plenty of rope to hang themselves with if you're depending on them for a front end application. For example they can rename a column to something else, which would then break everything that refers to that column in my app. Or they can delete or add a column which would mess up the GUI that makes assumptions around the availability of the columns.

**Comment by allthesignals** [comment]
Regarding your last point, there are user authentication levels in Fieldbook, so certain users could add and edit data but never modify table structure (columns, types, etc.).

**Comment by mzagaja** [comment]
Closing this since we decided not to let users edit data in the browser. Instead users will edit data in ICIMS and it will be imported.
