### ISSUE TITLE
Production Punchlist

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#15]
- [x] Setup and whitelist prod server
- [x] Setup the grid system on the prod database
- [x] Figure out what I need to do with Heroku and Git LFS
- [x] Import credentials for Twilio and Mapzen
- [x] Add 'https://dyee-dashboard.pagefrontapp.com/' to the KNOWN_HOSTS environment variable
- [x] Setup SSL/HTTPS

**Comment by mzagaja** [comment]
I filed a support ticket with Heroku about the Git LFS repo. Heroku's support documentation suggests they don't support git lfs, but I feel like there should at least be a way to deploy the repo without the LFS files included and then manually load those into the SQL database. Otherwise I may end up having to use a vanilla Ubuntu server.

**Comment by mzagaja** [comment]
Heroku does not support Git LFS so spent today setting up a production server on Amazon LightSail.

**Comment by mzagaja** [comment]
Chris Starkey whitelisted the server from iCIMS. Tomorrow we need to decide on a domain name and setup SSL. Then we need to clone this thing into a staging server as well. The grid system is currently importing to db.live.mapc.org.

**Comment by allthesignals** [comment]
Front end app is deployed - just need domains with SSL & known hosts set.

**Comment by mzagaja** [comment]
KNOWN_HOSTS is now set on prod. Just need to setup a domain/SSL.

**Comment by mzagaja** [comment]
Grid system is now up. I sent an e-mail to it help to request a DNS A record for dyee.mapc.org to point to the web server. Then I should be able to setup an SSL cert.

**Comment by mzagaja** [comment]
SSL is working as of yesterday. Amazon LightSail has its own firewall that had to have port 443 opened on it. Took four hours of poking at the server to figure out this was an issue. Everything is now alive!
