### ISSUE TITLE
Prevent Applicants from Being Selected by More Than One Direct Selection Site

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#161]
In direct selection, the last time applicants could be picked by more than one job site. When an applicant is offered a position by a job site, they should be removed from the list of candidates that other job sites can select until they no longer have an open offer (or they accept an offer).

**Comment by mzagaja** [comment]
@ericyoungberg Do you use the `GET /api/applicants` index action endpoint for anything other than grabbing applicants for the CBO dashboard picker? If not, then I can just filter it to not return any applicant that has an offer. Otherwise, I can make a separate endpoint or param that can be requested to do the same. Let me know what path forward makes the most sense.

**Comment by arouault** [comment]
@ericyoungberg ping!

**Comment by ericyoungberg** [comment]
Let's filter out the applicants that have offers as you suggested. I don't see why I would need them.

**Comment by mzagaja** [comment]
@arouault pong
