### ISSUE TITLE
Flag Under Age Applicants in Database

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#162]
In the partner dashboard young people whose birthday indicates they are under 15 years old should be flagged or highlighted in some way.

**Comment by ericyoungberg** [comment]
We recently discussed that these users will be filtered out when being imported from ICIMs, right? I think we ended up on a decision where there is hardly a point to flag youth who are not fit for the program.

**Comment by mzagaja** [comment]
Closing as WONTFIX since this is better handled in ICIMS before the import and we lack policy guidance from YEE on the specific rule (which might change from year to year anyways).
