### ISSUE TITLE
Modify endpoint for sending out text messages to matched youth from lottery

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/youth-match-v2#178]
Very much like #176 but this time with text messages.

**Comment by mzagaja** [comment]
So this endpoint exists currently as:
`POST     /api/outgoing_messages(.:format)                            outgoing_messages#create`

It will send the message to "chosen" applicants which are defined as the number of applicants equal to the number of currently open positions. However, open_positions is calculated without accounting for offers within our system. It probably should be switched to text the most recent batch of matched applicants by looking at the offers table by me.
