### ISSUE TITLE
Add Button to Build Travel Time Scores for Applicants

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#185]
`travel_time_scores POST     /api/travel_time_scores(.:format)                           travel_time_scores#create`

Note: This is a task that will take a long time as it generates a huge number of Sidekiq jobs (~1.6 million for the last applicants v. positions calculations). Then it needs to actually make the calculations. Then after this is done they can run the build preference scores task.

**Comment by arouault** [comment]
Not pursuing this path anymore.
