### ISSUE TITLE
Update bins and fields for ICIMs job import and import jobs data

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#20]
Update bins and fields from Linda for Jobs, import once Deron has loaded the data manually

**Comment by mzagaja** [comment]
We went through the fields for job recquistions and agreed that we would include in the e-mail to the person being offered the job the following fields: Job overview, job responsibilities, minimum qualifications, salary, and position type. Linda showed Matt where those fields existed in the iCIMS job requisition creation screen so he can refer back to them for the iCIMS names. Matt will follow-up with Chris Starkey to make sure he can query all of these from the API.

**Comment by mzagaja** [comment]
Putting this into 1.1 because our position information for this launch was pulled from an excel spreadsheet and some rake tasks that did information matching, so we do not need this for this year.
