### ISSUE TITLE
Authentication for Application

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#23]
Login for staff using google logins

**Comment by mzagaja** [comment]
The app needs an authentication and authorization system for users. The system should work as follows:

- DYEE staff should be able to login and see the dashboard
- CBO Partners should be able to login and see youth that have expressed interest in returning to their job site and youth that want to interview at their job site. They need to be able to then update the status of youth in their pipeline.
- Youth should be able to click an e-mail link that logs them in and lets them select jobs that interest them to update their profile with.

**Comment by mzagaja** [comment]
```
Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views
```

**Comment by mzagaja** [comment]
They removed token authentication from Devise by default due to security issues but we can add it back in using https://gist.github.com/josevalim/fb706b1e933ef01e4fb6.
