### ISSUE TITLE
Ability to Evaluate and fix erroneous addresses in DYEE Staff Interface

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#24]
Allow user to view the geocoded point and address and fix errors in the browser.

**Comment by mzagaja** [comment]
This does not seem achievable for 1.0 at this time. @arouault we need to decide how we will handle young people without good addresses for lottery purposes.

**Comment by mzagaja** [comment]
Closing this because address validations can/should happen in ICIMS before import.
