### ISSUE TITLE
Applicants Should Receive an E-Mail Invite To Apply to Jobs

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#37]
A DYEE staff member should be able to click a button to e-mail all the applicants so far and invite them to apply to specific jobs. When an applicant clicks the button they should land at an interface that lets them indicate interest in jobs. The app should poll ICIMS for new applicants every ten minutes or so and send e-mails to any new applicants.

We are currently waiting on Deron to provide e-mail text and information on who it is from.

**Comment by allthesignals** [comment]
@mzagaja Hi Matt, here's an example URL: http://youthjobs.mapc.org/jobs?email=[email]&token=[token]. The url params are: `email` and `token`.

**Comment by mzagaja** [comment]
@allthesignals Just want to double check, is it not https?

**Comment by mzagaja** [comment]
Ok I just need the content and this should be good to go.
