### ISSUE TITLE
Only allow youth to flag interest in a max of 10 jobs

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#48]
Only allow youth to flag interest in a max of 10 jobs

**Comment by mzagaja** [comment]
Found a good pattern to follow for this at http://stackoverflow.com/questions/2263267/limit-number-of-objects-in-has-many-association

**Comment by allthesignals** [comment]
Yeah it'll be important to validate this as well as communicate it clearly in the UI - a shrewd young person might try to hit the API! @arouault if you have thoughts on how this communicate works in the UI, let me know!

**Comment by arouault** [comment]
+1 let's do this in the UI
