### ISSUE TITLE
Login System for CBOs

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#68]
For the CBO login system we will follow the same pattern as for you the young people. However instead of sending them to the front end for the job picker they will go to the front end for the applicant picker. @allthesignals we will need to make sure that front end accepts the same email and token params as the job picker. Presumably authorization will be taken care of by the fact that a user without an associated applicant will not see jobs in the job picker, and a user without an associated CBO for their profile will not see applicants in the applicant picker.

The sticky wicket with this is that we currently have "rehire_sites", a one off model object we use to show youth that might be rehired. In some ways it feels like rehire_sites should evolve to simply be job sites, but it is definitely not that. It may well be better to introduce a job_sites model that can has_many positions and belongs to a user. A rake task will have to be written to populate this from some source somewhere (presumably a copy of the spreadsheet of users from Deron). The especially tricky (or potentially tedious part) is that there may be no magic to link positions to these job sites. Tomorrow's mission will be searching for one, or spending some hours manually entering it into a spreadsheet.

**Comment by allthesignals** [comment]
Carrying over my comment from before:
This could be messy - should we explicitly define a user_type? An enum would do. Do you mean Devise authorizing specific requests? For example, an authorized youth applicant can only make GET and PATCH requests to the /positions endpoint but not to the CBO view (specifically, application)?
