### ISSUE TITLE
Things to refactor

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#74]
Need to figure out why nested routes don't work right. 

We are not using the owned action in the positions controller. Need to figure out better way to serve the positions owned by the requesting user. 

The sites model is a bit ugly.

**Comment by mzagaja** [comment]
@allthesignals Found this pattern for nested and un-nested resources, but more Googling seems to reveal that your pattern is actually not far off from the accepted practice: http://stackoverflow.com/questions/21766957/how-to-manage-both-nested-and-not-nested-resources

**Comment by allthesignals** [comment]
@mzagaja Rails docs seem to suggest nested resources should work out of the box... see the table here: http://guides.rubyonrails.org/v3.2.9/routing.html#nested-resources. 

![image](https://cloud.githubusercontent.com/assets/5004319/24572128/098fc7fc-1644-11e7-84a6-4114edd6541b.png)

Maybe it's not saying it will handle the controller logic of only getting particular related resources when they're nested? Thoughts? 

It's just sad to have to write all those methods!

**Comment by mzagaja** [comment]
So http://railscasts.com/episodes/139-nested-resources?autoplay=true at 4m mark shows a pattern whereby the child nested controller needs to be modified to summon the parent nested resource and then summon the child resources through the parent. If we follow this pattern to refactor your code it'd be something like

```
def index
  @position = Position.find(params[:position_id])
  @applicants = @position.applicants.find(params[:id])
end
```
instead of  `@applicants = Applicant.includes(:positions).where('positions.id' => params[:position_id])`

The StackOverflow above demonstrates that if you have both nested and un-nested routes, that your if params logic is unavoidable. Definitely agree that it could be more elegant.
