### ISSUE TITLE
Applicants resource index method can filter by interest categories

### ISSUE THREAD

**Issue by allthesignals** [MAPC/youth-match-v2#86]
The applicants endpoint should allow for filter based on the _set intersection between applicant's `interests` and a given input list of categories_. 

Request:
`GET /applicants?specialFilter[interest]=sports,administration,peanut_butter`

In SQL, this might look like an `IN ('string','string','string')`, but it's not clear how to parse the JSON column type to support this. Maybe there's a Rails gem. 

@mzagaja any advice is appreciated.

**Comment by mzagaja** [comment]
I think the approach here would be to set up an appropriate scope on the applicants method.

```
# preferences->state = 'SP' AND preferences->city = 'São Paulo'
User.where('preferences @> ?', {city: 'San Francisco', state: 'CA'}.to_json)
```

Then we can setup a sub-controller to allow grabbing the index of these with the appropriate param passed.

**Comment by allthesignals** [comment]
@mzagaja alright, could you take a stab at that? I've never worked with sub-controllers.

**Comment by mzagaja** [comment]
Sure!

**Comment by mzagaja** [comment]
Figured out the query to get things in an array is `Applicant.where("interests  && ARRAY[?]::varchar[]", ["Peer Leadership", "dummy"])`

Just have to figure out sub-controllers and then push my solution.
