### ISSUE TITLE
Add dyee-dashboard.staging.pagefrontapp.com to KNOWN_HOSTS

### ISSUE THREAD

**Issue by allthesignals** [MAPC/youth-match-v2#94]
Can we add the staging environment, dyee-dashboard.staging.pagefrontapp.com, to KNOWN_HOSTS env variable? Thank you.

**Comment by mzagaja** [comment]
Is that with http or https prefix?

**Comment by allthesignals** [comment]
Oops, @mzagaja https://dyee-dashboard.staging.pagefrontapp.com/

**Comment by mzagaja** [comment]
Ok it's alive, give it a shot.
