### ISSUE TITLE
Applicants controller index action does not filter with multiple interests (only one)

### ISSUE THREAD

**Issue by allthesignals** [MAPC/youth-match-v2#96]
applicants?[interests]=Peer Leadership <----------------------------------------- works
applicants?[interests]=Sports, Fitness and/or Recreation <------------------------ works
applicants?[interests]=Peer Leadership,Sports, Fitness and/or Recreation <------- not works

Maybe it's checking for applicants whose interests match ALL of the categories rather than ANY? If that's the case, it's likely that at least SOME should be interested in both "Peer Leadership" and "Sports, Fitness and/or Recreation", but maybe it's something else.

**Comment by mzagaja** [comment]
Try grouping with quotes to avoid breaking with the comma in sports:

`Peer Leadership,Sports, Fitness and/or Recreation` should be `"Peer Leadership,"Sports, Fitness and/or Recreation"`

**Comment by allthesignals** [comment]
No luck - the quotes actually throw it off more it seems.

**Comment by mzagaja** [comment]
Ok turns out the answer is at http://guides.rubyonrails.org/action_controller_overview.html#hash-and-array-parameters

Guess I had figured this out before but then failed to remember. No changes necessary on my end, but try this format and let me know.

**Comment by allthesignals** [comment]
Okay, gotcha, @mzagaja, I'm still struggling to get this to work with the new syntax.

`http://localhost:3000/api/applicants?interests[]=Peer Leadership,Health Care` yields an empty array (no results).

`http://localhost:3000/api/applicants?interests[]="Peer Leadership","Health Care"` yields an empty array (no results).

Which URL are you using to test this? Maybe you can copy the Postman query and send me so I can test it on my machine.

Thanks.

**Comment by mzagaja** [comment]
The format is `http://127.0.0.1:3000/api/applicants?interests[]=Peer Leadership&interests[]=Sports,Fitness and/or Recreation`

**Comment by allthesignals** [comment]
Gotcha - thanks for the example
